use crate::model::TerrainType::*;
use crate::model::Card;

pub const CARDS: [Card; 68] = [
    // TODO uncomment monasteries when there is better visualisation
    // Card { sides: [FIELD, FIELD, FIELD, FIELD] },
    // Card { sides: [FIELD, FIELD, FIELD, FIELD] },
    // Card { sides: [FIELD, FIELD, FIELD, FIELD] },
    // Card { sides: [FIELD, FIELD, FIELD, FIELD] },
    Card { sides: [FIELD, TOWN, FIELD, FIELD] },
    Card { sides: [FIELD, TOWN, FIELD, FIELD] },
    Card { sides: [FIELD, TOWN, FIELD, FIELD] },
    Card { sides: [FIELD, TOWN, FIELD, FIELD] },
    Card { sides: [FIELD, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, FIELD, TOWN, FIELD] },
    Card { sides: [TOWN, FIELD, TOWN, FIELD] },
    Card { sides: [TOWN, FIELD, TOWN, FIELD] },
    Card { sides: [TOWN, FIELD, TOWN, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, TOWN, FIELD, FIELD] },
    Card { sides: [TOWN, FIELD, TOWN, FIELD] },
    Card { sides: [TOWN, FIELD, TOWN, FIELD] },
    Card { sides: [TOWN, TOWN, TOWN, FIELD] },
    Card { sides: [TOWN, TOWN, TOWN, FIELD] },
    Card { sides: [TOWN, TOWN, TOWN, FIELD] },
    Card { sides: [TOWN, TOWN, TOWN, FIELD] },
    Card { sides: [TOWN, TOWN, TOWN, TOWN] },
    Card { sides: [FIELD, FIELD, FIELD, ROAD] },
    Card { sides: [FIELD, FIELD, FIELD, ROAD] },
    Card { sides: [TOWN, TOWN, TOWN, ROAD] },
    Card { sides: [TOWN, TOWN, TOWN, ROAD] },
    Card { sides: [TOWN, TOWN, TOWN, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [FIELD, ROAD, FIELD, ROAD] },
    Card { sides: [ROAD, TOWN, ROAD, FIELD] },
    Card { sides: [ROAD, TOWN, ROAD, FIELD] },
    Card { sides: [ROAD, TOWN, ROAD, FIELD] },
    Card { sides: [ROAD, TOWN, ROAD, FIELD] },
    Card { sides: [TOWN, TOWN, ROAD, ROAD] },
    Card { sides: [TOWN, TOWN, ROAD, ROAD] },
    Card { sides: [TOWN, TOWN, ROAD, ROAD] },
    Card { sides: [TOWN, TOWN, ROAD, ROAD] },
    Card { sides: [TOWN, TOWN, ROAD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, FIELD, FIELD, ROAD] },
    Card { sides: [ROAD, TOWN, FIELD, ROAD] },
    Card { sides: [ROAD, TOWN, FIELD, ROAD] },
    Card { sides: [ROAD, TOWN, FIELD, ROAD] },
    Card { sides: [FIELD, TOWN, ROAD, ROAD] },
    Card { sides: [FIELD, TOWN, ROAD, ROAD] },
    Card { sides: [FIELD, TOWN, ROAD, ROAD] },
    Card { sides: [ROAD, FIELD, ROAD, ROAD] },
    Card { sides: [ROAD, FIELD, ROAD, ROAD] },
    Card { sides: [ROAD, FIELD, ROAD, ROAD] },
    Card { sides: [ROAD, FIELD, ROAD, ROAD] },
    Card { sides: [ROAD, TOWN, ROAD, ROAD] },
    Card { sides: [ROAD, TOWN, ROAD, ROAD] },
    Card { sides: [ROAD, TOWN, ROAD, ROAD] },
    Card { sides: [ROAD, ROAD, ROAD, ROAD] },
];